### ISSUE TITLE
Add Instrumentation to Config and PostHandler

### ISSUE THREAD

**Issue by maarek** [networknt/light-graphql-4j#38]
What are your thoughts on configuring Instrumentation in the service.yml and then injecting those classes into the GraphQL instance in the GraphqlPostHandler? I see some instrumentation tied to Subscriptions but not to post requests and it doesn't seem to be configurable. 

[http://graphql-java.readthedocs.io/en/latest/instrumentation.html#instrumentation](http://graphql-java.readthedocs.io/en/latest/instrumentation.html#instrumentation)

**Comment by NicholasAzar** [comment]
@maarek Providing the services that are leveraging light-graphql with a method of injecting instrumention absolutely makes sense. Really appreciate you bringing this to our attention.
I expect we should consider allowing injectable instrumentation both for queries/mutations (post requests) as well as subscriptions.

Let me take a look at the implementation details to see how it can fit in with the existing codebase. I'll keep this issue updated as soon as I get a more clear picture.
If you have any more information that you think might help, please let us know.

**Comment by NicholasAzar** [comment]
@maarek is this ok to close?
